<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Check login and logout successfully"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="52.498">
    <properties></properties>

            <testcase
                name="signIn"
                time="52.498"
                classname="pages.TestPageLoginSecurity">

            <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
                org.testng.Assert.fail(Assert.java:96)org.testng.Assert.failNotEquals(Assert.java:776)org.testng.Assert.assertTrue(Assert.java:44)org.testng.Assert.assertTrue(Assert.java:54)pages.PageDashBoard.consignURL(PageDashBoard.java:78)pages.TestPageLoginSecurity.signIn(TestPageLoginSecurity.java:46)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:567)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)org.testng.internal.Invoker.invokeMethod(Invoker.java:583)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:648)org.testng.TestRunner.run(TestRunner.java:505)org.testng.SuiteRunner.runTest(SuiteRunner.java:455)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)org.testng.SuiteRunner.run(SuiteRunner.java:364)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)org.testng.TestNG.runSuitesLocally(TestNG.java:1137)org.testng.TestNG.runSuites(TestNG.java:1049)org.testng.TestNG.run(TestNG.java:1017)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </failure>
    </testcase>


</testsuite>
